export const SET_DATA = 'SET_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const RESET_DATA = 'RESET_DATA';
export const START_DATA_FETCHING = 'START_DATA_FETCHING';
export const INIT_ONE_SIGNAL_DEVICE_START = 'INIT_ONE_SIGNAL_DEVICE_START';
export const INIT_ONE_SIGNAL_DEVICE_END = 'INIT_ONE_SIGNAL_DEVICE_END';

export default {
  SET_DATA,
  UPDATE_DATA,
  START_DATA_FETCHING,
  INIT_ONE_SIGNAL_DEVICE_START,
  INIT_ONE_SIGNAL_DEVICE_END,
};
